/*
Copyright (C) 2015 Matthew Gefaller
This file is part of LeafStyle.

LeafStyle is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

LeafStyle is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LeafStyle. If not, see <http://www.gnu.org/licenses/>.
*/

using System;

namespace LeafStyle
{
    public enum Property
    {
        AlignContent,
        AlignItems,
        AlignSelf,
        Animation,
        AnimationDelay,
        AnimationDirection,
        AnimationDuration,
        AnimationFillMode,
        AnimationIterationCount,
        AnimationName,
        AnimationPlayState,
        AnimationTimingFunction,
        BackfaceVisibility,
        Background,
        BackgroundAttachment,
        BackgroundClip,
        BackgroundColor,
        BackgroundImage,
        BackgroundOrigin,
        BackgroundPosition,
        BackgroundRepeat,
        BackgroundSize,
        Border,
        BorderBottom,
        BorderBottomColor,
        BorderBottomLeftRadius,
        BorderBottomRightRadius,
        BorderBottomStyle,
        BorderBottomWidth,
        BorderCollapse,
        BorderColor,
        BorderImage,
        BorderImageOutset,
        BorderImageRepeat,
        BorderImageSlice,
        BorderImageSource,
        BorderImageWidth,
        BorderLeft,
        BorderLeftColor,
        BorderLeftStyle,
        BorderLeftWidth,
        BorderRadius,
        BorderRight,
        BorderRightColor,
        BorderRightStyle,
        BorderRightWidth,
        BorderSpacing,
        BorderStyle,
        BorderTop,
        BorderTopColor,
        BorderTopLeftRadius,
        BorderTopRightRadius,
        BorderTopStyle,
        BorderTopWidth,
        BorderWidth,
        Bottom,
        BoxShadow,
        BoxSizing,
        CaptionSide,
        Clear,
        Clip,
        Color,
        ColumnCount,
        ColumnFill,
        ColumnGap,
        ColumnRule,
        ColumnRuleColor,
        ColumnRuleStyle,
        ColumnRuleWidth,
        ColumnSpan,
        ColumnWidth,
        Columns,
        // Content is handeled at the element level
        // CounterIncrement is handeled at the element level
        // CounterReset is handeled at the element level
        Cursor,
        Direction,
        Display,
        EmptyCells,
        Flex,
        FlexBasis,
        FlexDirection,
        FlexFlow,
        FlexGrow,
        FlexShrink,
        FlexWrap,
        Float,
        Font,
        FontFace,
        FontFamily,
        FontSize,
        FontSizeAdjust,
        FontStretch,
        FontStyle,
        FontVariant,
        FontWeight,
        HangingPunctuation,
        Height,
        Icon,
        JustifyContent,
        Keyframes,
        Left,
        LetterSpacing,
        LineHeight,
        ListStyle,
        ListStyleImage,
        ListStylePosition,
        ListStyleType,
        Margin,
        MarginBottom,
        MarginLeft,
        MarginRight,
        MarginTop,
        MaxHeight,
        MaxWidth,
        Media,
        MinHeight,
        MinWidth,
        NavDown,
        NavIndex,
        NavLeft,
        NavRight,
        NavUp,
        Opacity,
        Order,
        Outline,
        OutlineColor,
        OutlineOffset,
        OutlineStyle,
        OutlineWidth,
        Overflow,
        OverflowX,
        OverflowY,
        Padding,
        PaddingBottom,
        PaddingLeft,
        PaddingRight,
        PaddingTop,
        PageBreakAfter,
        PageBreakBefore,
        PageBreakInside,
        Perspective,
        PerspectiveOrigin,
        Position,
        Quotes,
        Resize,
        Right,
        TabSize,
        TableLayout,
        TextAlign,
        TextAlignLast,
        TextDecoration,
        TextDecorationColor,
        TextDecorationLine,
        TextDecorationStyle,
        TextIndent,
        TextJustify,
        TextOverflow,
        TextShadow,
        TextTransform,
        Top,
        Transform,
        TransformOrigin,
        TransformStyle,
        Transition,
        TransitionDelay,
        TransitionDuration,
        TransitionProperty,
        TransitionTimingFunction,
        UnicodeBidi,
        VerticalAlign,
        Visibility,
        WhiteSpace,
        Width,
        WordBreak,
        WordSpacing,
        WordWrap,
        ZIndex
    }
}
