/*
Copyright (C) 2015 Matthew Gefaller
This file is part of LeafStyle.

LeafStyle is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

LeafStyle is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LeafStyle. If not, see <http://www.gnu.org/licenses/>.
*/

using Microsoft.Xna.Framework;
using System.Collections.Generic;

namespace LeafStyle
{
    public static partial class Value
    {
        public static Dictionary<string, Color> ColorContainer = new Dictionary<string, Color>()
        {
            { "aliceblue", Microsoft.Xna.Framework.Color.AliceBlue },
            { "antiquewhite", Microsoft.Xna.Framework.Color.AntiqueWhite },
            { "aqua", Microsoft.Xna.Framework.Color.Aqua },
            { "aquamarine", Microsoft.Xna.Framework.Color.Aquamarine },
            { "azure", Microsoft.Xna.Framework.Color.Azure },
            { "beige", Microsoft.Xna.Framework.Color.Beige },
            { "bisque", Microsoft.Xna.Framework.Color.Bisque },
            { "black", Microsoft.Xna.Framework.Color.Black },
            { "blanchedalmond", Microsoft.Xna.Framework.Color.BlanchedAlmond },
            { "blue", Microsoft.Xna.Framework.Color.Blue },
            { "blueviolet", Microsoft.Xna.Framework.Color.BlueViolet },
            { "brown", Microsoft.Xna.Framework.Color.Brown },
            { "burlywood", Microsoft.Xna.Framework.Color.BurlyWood },
            { "cadetblue", Microsoft.Xna.Framework.Color.CadetBlue },
            { "chartreuse", Microsoft.Xna.Framework.Color.Chartreuse },
            { "chocolate", Microsoft.Xna.Framework.Color.Chocolate },
            { "coral", Microsoft.Xna.Framework.Color.Coral },
            { "cornflowerblue", Microsoft.Xna.Framework.Color.CornflowerBlue },
            { "cornsilk", Microsoft.Xna.Framework.Color.Cornsilk },
            { "crimson", Microsoft.Xna.Framework.Color.Crimson },
            { "cyan", Microsoft.Xna.Framework.Color.Cyan },
            { "darkblue", Microsoft.Xna.Framework.Color.DarkBlue },
            { "darkcyan", Microsoft.Xna.Framework.Color.DarkCyan },
            { "darkgray", Microsoft.Xna.Framework.Color.DarkGray },
            { "darkgreen", Microsoft.Xna.Framework.Color.DarkGreen },
            { "darkkhaki", Microsoft.Xna.Framework.Color.DarkKhaki },
            { "darkmagenta", Microsoft.Xna.Framework.Color.DarkMagenta },
            { "darkolivegreen", Microsoft.Xna.Framework.Color.DarkOliveGreen },
            { "darkorange", Microsoft.Xna.Framework.Color.DarkOrange },
            { "darkorchid", Microsoft.Xna.Framework.Color.DarkOrchid },
            { "darkred", Microsoft.Xna.Framework.Color.DarkRed },
            { "darksalmon", Microsoft.Xna.Framework.Color.DarkSalmon },
            { "darkseagreen", Microsoft.Xna.Framework.Color.DarkSeaGreen },
            { "darkslateblue", Microsoft.Xna.Framework.Color.DarkSlateBlue },
            { "darkslategray", Microsoft.Xna.Framework.Color.DarkSlateGray },
            { "darkturquoise", Microsoft.Xna.Framework.Color.DarkTurquoise },
            { "darkviolet", Microsoft.Xna.Framework.Color.DarkViolet },
            { "deeppink", Microsoft.Xna.Framework.Color.DeepPink },
            { "deepskyblue", Microsoft.Xna.Framework.Color.DeepSkyBlue },
            { "dimgray", Microsoft.Xna.Framework.Color.DimGray },
            { "dodgerblue", Microsoft.Xna.Framework.Color.DodgerBlue },
            { "floralwhite", Microsoft.Xna.Framework.Color.FloralWhite },
            { "forestgreen", Microsoft.Xna.Framework.Color.ForestGreen },
            { "fuchsia", Microsoft.Xna.Framework.Color.Fuchsia },
            { "gainsboro", Microsoft.Xna.Framework.Color.Gainsboro },
            { "ghostwhite", Microsoft.Xna.Framework.Color.GhostWhite },
            { "gold", Microsoft.Xna.Framework.Color.Gold },
            { "gray", Microsoft.Xna.Framework.Color.Gray },
            { "green", Microsoft.Xna.Framework.Color.Green },
            { "greenyellow", Microsoft.Xna.Framework.Color.GreenYellow },
            { "hotpink", Microsoft.Xna.Framework.Color.HotPink },
            { "indianred", Microsoft.Xna.Framework.Color.IndianRed },
            { "indigo", Microsoft.Xna.Framework.Color.Indigo },
            { "ivory", Microsoft.Xna.Framework.Color.Ivory },
            { "khaki", Microsoft.Xna.Framework.Color.Khaki },
            { "lavender", Microsoft.Xna.Framework.Color.Lavender },
            { "lavenderblush", Microsoft.Xna.Framework.Color.LavenderBlush },
            { "lawngreen", Microsoft.Xna.Framework.Color.LawnGreen },
            { "lemonchiffon", Microsoft.Xna.Framework.Color.LemonChiffon },
            { "lightblue", Microsoft.Xna.Framework.Color.LightBlue },
            { "lightcoral", Microsoft.Xna.Framework.Color.LightCoral },
            { "lightcyan", Microsoft.Xna.Framework.Color.LightCyan },
            { "lightgray", Microsoft.Xna.Framework.Color.LightGray },
            { "lightgreen", Microsoft.Xna.Framework.Color.LightGreen },
            { "lightpink", Microsoft.Xna.Framework.Color.LightPink },
            { "lightsalmon", Microsoft.Xna.Framework.Color.LightSalmon },
            { "lightseagreen", Microsoft.Xna.Framework.Color.LightSeaGreen },
            { "lightskyblue", Microsoft.Xna.Framework.Color.LightSkyBlue },
            { "lightslategray", Microsoft.Xna.Framework.Color.LightSlateGray },
            { "lightsteelblue", Microsoft.Xna.Framework.Color.LightSteelBlue },
            { "lightyellow", Microsoft.Xna.Framework.Color.LightYellow },
            { "lime", Microsoft.Xna.Framework.Color.Lime },
            { "limegreen", Microsoft.Xna.Framework.Color.LimeGreen },
            { "linen", Microsoft.Xna.Framework.Color.Linen },
            { "magenta", Microsoft.Xna.Framework.Color.Magenta },
            { "maroon", Microsoft.Xna.Framework.Color.Maroon },
            { "mediumblue", Microsoft.Xna.Framework.Color.MediumBlue },
            { "mediumorchid", Microsoft.Xna.Framework.Color.MediumOrchid },
            { "mediumpurple", Microsoft.Xna.Framework.Color.MediumPurple },
            { "mediumseagreen", Microsoft.Xna.Framework.Color.MediumSeaGreen },
            { "mediumslateblue", Microsoft.Xna.Framework.Color.MediumSlateBlue },
            { "mediumspringgreen", Microsoft.Xna.Framework.Color.MediumSpringGreen },
            { "mediumturquoise", Microsoft.Xna.Framework.Color.MediumTurquoise },
            { "mediumvioletred", Microsoft.Xna.Framework.Color.MediumVioletRed },
            { "midnightblue", Microsoft.Xna.Framework.Color.MidnightBlue },
            { "mintcream", Microsoft.Xna.Framework.Color.MintCream },
            { "mistyrose", Microsoft.Xna.Framework.Color.MistyRose },
            { "moccasin", Microsoft.Xna.Framework.Color.Moccasin },
            { "navajowhite", Microsoft.Xna.Framework.Color.NavajoWhite },
            { "navy", Microsoft.Xna.Framework.Color.Navy },
            { "oldLace", Microsoft.Xna.Framework.Color.OldLace },
            { "olive", Microsoft.Xna.Framework.Color.Olive },
            { "olivedrab", Microsoft.Xna.Framework.Color.OliveDrab },
            { "orange", Microsoft.Xna.Framework.Color.Orange },
            { "orangeRed", Microsoft.Xna.Framework.Color.OrangeRed },
            { "orchid", Microsoft.Xna.Framework.Color.Orchid },
            //{ "palegoldenrod", Microsoft.Xna.Framework.Color.PaleGoldenRod }, // Not defined in Microsoft.Xna.Framework.Color
            { "palegreen", Microsoft.Xna.Framework.Color.PaleGreen },
            { "paleturquoise", Microsoft.Xna.Framework.Color.PaleTurquoise },
            { "palevioletred", Microsoft.Xna.Framework.Color.PaleVioletRed },
            { "papayawhip", Microsoft.Xna.Framework.Color.PapayaWhip },
            { "peachpuff", Microsoft.Xna.Framework.Color.PeachPuff },
            { "peru", Microsoft.Xna.Framework.Color.Peru },
            { "pink", Microsoft.Xna.Framework.Color.Pink },
            { "plum", Microsoft.Xna.Framework.Color.Plum },
            { "powderblue", Microsoft.Xna.Framework.Color.PowderBlue },
            { "purple", Microsoft.Xna.Framework.Color.Purple },
            { "red", Microsoft.Xna.Framework.Color.Red },
            { "rosybrown", Microsoft.Xna.Framework.Color.RosyBrown },
            { "royalblue", Microsoft.Xna.Framework.Color.RoyalBlue },
            { "saddlebrown", Microsoft.Xna.Framework.Color.SaddleBrown },
            { "salmon", Microsoft.Xna.Framework.Color.Salmon },
            { "sandybrown", Microsoft.Xna.Framework.Color.SandyBrown },
            { "seagreen", Microsoft.Xna.Framework.Color.SeaGreen },
            { "seashell", Microsoft.Xna.Framework.Color.SeaShell },
            { "sienna", Microsoft.Xna.Framework.Color.Sienna },
            { "silver", Microsoft.Xna.Framework.Color.Silver },
            { "skyblue", Microsoft.Xna.Framework.Color.SkyBlue },
            { "slateblue", Microsoft.Xna.Framework.Color.SlateBlue },
            { "slategray", Microsoft.Xna.Framework.Color.SlateGray },
            { "snow", Microsoft.Xna.Framework.Color.Snow },
            { "springgreen", Microsoft.Xna.Framework.Color.SpringGreen },
            { "steelblue", Microsoft.Xna.Framework.Color.SteelBlue },
            { "tan", Microsoft.Xna.Framework.Color.Tan },
            { "teal", Microsoft.Xna.Framework.Color.Teal },
            { "thistle", Microsoft.Xna.Framework.Color.Thistle },
            { "tomato", Microsoft.Xna.Framework.Color.Tomato },
            { "turquoise", Microsoft.Xna.Framework.Color.Turquoise },
            { "violet", Microsoft.Xna.Framework.Color.Violet },
            { "wheat", Microsoft.Xna.Framework.Color.Wheat },
            { "white", Microsoft.Xna.Framework.Color.White },
            { "whitesmoke", Microsoft.Xna.Framework.Color.WhiteSmoke },
            { "yellow", Microsoft.Xna.Framework.Color.Yellow },
            { "yellowgreen", Microsoft.Xna.Framework.Color.YellowGreen }
        };
    }
}
